### ISSUE TITLE
Compile on macOS

### ISSUE THREAD

**Issue by TheFermiSea** [GiantMolecularCloud/my-resume#10]
I am having issues compiling this on my local machine.  It claims that FontAwesome is not installed, although the package is definitely there.  Originally, I also had an issue with Carlito, but installing that font solved the issue.  I do not have any issues in Overleaf.  Any ideas?

**Comment by TheFermiSea** [comment]
I solved my own problem.  The FontAwesome font that comes with texlive must be properly installed by the following:

--find the location of FontAwesome:  located in /usr/local/texlive/2022/texmf-dist/fonts/opentype/public/fontawesome
--double click the file and install

**Comment by GiantMolecularCloud** [comment]
I suppose this might also depend on the TeX distribution. My local tests on macOS with macTeX did not require explicite installation of the fonts.
Edit: In hindsight, I probably had FontAwesome installed already ...

Which TeX distribution did you use? This detail might help others with the same or a similar problem.

**Comment by zyv** [comment]
I have the same problem with macTeX 2022. Somehow apparently it requires extra configuration to pick up its own OTF fonts :( installing the font in the user Library fixes the problem.
