### ISSUE TITLE
Compiling in VS Code

### ISSUE THREAD

**Issue by TheFermiSea** [GiantMolecularCloud/my-resume#11]
For anyone who is having trouble compiling in VS Code using LaTeX Workshop, here is how I solved the issue:

uncheck the following:\
"Latex-workshop › Latex › Build: Force Recipe Usage"
in extension settings.  
Then add:
% !TeX program = xelatex
to the top of the file. This will override the default and use xelatex.

You could also change the recipe in the settings.json, but I found this solution to be much more simple.

Good luck in the interview!

**Comment by GiantMolecularCloud** [comment]
Thanks for the solution!
I expanded the readme to reference your solution for VS Code.
