### ISSUE TITLE
Remove photo

### ISSUE THREAD

**Issue by ErfanMowlaei** [GiantMolecularCloud/my-resume#12]
Thank you for this decent template. I need to remove the photo from it, and give its space to the text. How is that possible?

**Comment by GiantMolecularCloud** [comment]
That should work by leaving out the `\photo{}` command, i.e. just give `\name{}` and `\tag{}` before `\makeheader`:
```
\name{my name}
\tagline{a tag line with text}
\makeheader
```
The code will then use all the available space to set the name and tag line.

**Comment by ErfanMowlaei** [comment]
It causes another problem. If the tagline is long, it will just get out of the header, while it will stay in the header if the photo is there.

**Comment by GiantMolecularCloud** [comment]
Fixed in 28897223321e51a7c6ce8bd48d46f36961de95cb
