### ISSUE TITLE
Right-aligning positions in `\job` pushes text too far right

### ISSUE THREAD

**Issue by zyv** [GiantMolecularCloud/my-resume#17]
Hi there,

Thank you for an interesting template!

I have been experimenting with right-aligning the positions in `\job`, but somehow the text is pushed way too far to the right. I have tried both `\raggedleft` and `\hfill` to the same effect.

Any ideas? Many thanks!

**Comment by zyv** [comment]
Answering my own question after I've got a moment to look into it:

My problem was due to minipages being too wide. If the width of both of them is set to `0.4` and `\hfill` is added between them, then everything works as expected and a `\hfill` before position name will make it right-aligned.

Why `0.49` or something isn't working is not exactly clear - maybe some margins appear from somewhere or something, but probably I'll sleep better if I wouldn't know.

**Comment by GiantMolecularCloud** [comment]
Glad you could figure it out. Right now I also can't tell why larger values do not work. You are probably right that a margin of some sort steal some of the available space. Once I have more time again, I will try to look into it.
