### ISSUE TITLE
Cv won't compile using xelatex

### ISSUE THREAD

**Issue by jjalvarezl** [GiantMolecularCloud/my-resume#3]
I do not know if I did not have a good xelatex version, but line 339 of my-resume.cls, command `\Ifthispageodd` is "undefined" when I use xelatex. I just wrote the first character in lower case like `\ifthispageodd` and it worked for me. It could be a suggestion in order to improve this really nice cv resume template.

**Comment by GiantMolecularCloud** [comment]
Thanks for noticing! 
Interestingly, I never had problems although the capital i in ifthispageodd was there in my oldest version of the .cls I could find. Overleaf is very forgiving regarding such errors, though.
