### ISSUE TITLE
Text in "singlesided" layout with empty highlightbar is not aligned correctly

### ISSUE THREAD

**Issue by DInfanger** [GiantMolecularCloud/my-resume#4]
Changing the layout to "singlesided" and leaving the highlightbar empty, the text of the mainbar is not aligned correctly. To create the picture below, I just downloaded the repository and changed "doublesided" to "singlesided".

![resume](https://user-images.githubusercontent.com/7227552/117941106-12b79c80-b30a-11eb-872b-9137256a796e.png)

> XeTeX, Version 3.141592653-2.6-0.999993 (MiKTeX 21.3) (preloaded format=xelatex 2021.5.12)

**Comment by GiantMolecularCloud** [comment]
Sorry that I did not look into this issue ealier and thank you to @leoTlr for fixing this issue!
