### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by Iizuki** [GiantMolecularCloud/my-resume#6]
This repository has no license, which implies that it cannot be used without a special permission. Yet, it's listed as CC-BY 4.0 in [overfeal](https://www.overleaf.com/latex/templates/my-resume/qxsxdtmknkfr).

Could you resolve the inconsistency by adding a CC-BY 4.0 license file to this repository?

**Comment by GiantMolecularCloud** [comment]
Thank you for pointing out the missing license! This template was meant to be shared freely, so I assigned the MIT license which fits better for software than CC-BY 4.0. On overleaf, I cannot simply change the license but need to resubmit and overwrite the template (which may or may not work as intended).

**Comment by GiantMolecularCloud** [comment]
Fixed by e5d81b9
