### ISSUE TITLE
Move Photo

### ISSUE THREAD

**Issue by TheFermiSea** [GiantMolecularCloud/my-resume#7]
I am trying to move the photo so it is centered between the header text and the right-edge of the page.  Any ideas?

**Comment by GiantMolecularCloud** [comment]
I am not sure if I understand what you want to achieve exactly.
The position of the photo and the header is set with nested minipages in [L250](https://github.com/GiantMolecularCloud/my-resume/blob/main/my-resume.cls#L250). To make the header smaller and leave a gap to the photo, you have to change the minipage widths in [L261](https://github.com/GiantMolecularCloud/my-resume/blob/main/my-resume.cls#L261) and [L265](https://github.com/GiantMolecularCloud/my-resume/blob/main/my-resume.cls#L265). 
Reduce the width by the page margin (defaults to 1cm) and add a hspace of width page margin before the photo. This should result in an equal distance from header text to photo and photo to page edge.

**Comment by GiantMolecularCloud** [comment]
This seems to have solved the issue. Closing.
