### ISSUE TITLE
corrupted example Image 

### ISSUE THREAD

**Issue by sulfur36** [GiantMolecularCloud/my-resume#8]
Not a big issue but for me the example image picture.jpg could not be rendered correctly.

Eye of GNOME 3.36.3 (Ubuntu default image viewer) gives the error message: 
`Error reading JPEG file (Not a JPEG file: starts with 0x0a 0x0a)`

The problem persists when viewing the resume.pdf with Evince 3.36.10, Libre Office Draw 7.3 and Inkscape 0.92.5.
This causes the pdf to be displayed without the image in the top right.
Weirdly enough Firefox and Chromium were able to display the pdf correctly. 

It took me a while to figure out that the issue was with the picture.jpg itself and not with my pdf viewers or the LaTex environment I used. 

Hope this saves someone some time.

I fixed my issue by converting the  with Gimp.
You may consider to swap out the example picture.jpg with the converted file:

![picture](https://user-images.githubusercontent.com/104072087/164222500-0f058057-b603-42d7-91b7-18ec78880f18.jpg)

**Comment by GiantMolecularCloud** [comment]
Interesting. Thank you for providing a fixed file. I replaced the original file with your version.

I created the original file with Pixelmator on macOS and did not experience any errors on macOS or Windows. Good to know that this can happen.
